const variableList = [
	{ name: 'PanPosition', variableId: 'PPos' },
	{ name: 'TiltPosition', variableId: 'TPos' },
	{ name: 'SlidePosition', variableId: 'SPos' },
	{ name: 'M4Position', variableId: 'MPos' },
	{ name: 'FocusPosition', variableId: 'FPos' },
	{ name: 'IrisPosition', variableId: 'IPos' },
	{ name: 'ZoomPosition', variableId: 'ZPos' },
	{ name: 'RollPosition', variableId: 'RPos' },
	{ name: 'PanIncrement', variableId: 'PStep' },
	{ name: 'TiltIncrement', variableId: 'TStep' },
	{ name: 'SlideIncrement', variableId: 'SStep' },
	{ name: 'M4Increment', variableId: 'MStep' },
	{ name: 'FocusIncrement', variableId: 'FStep' },
	{ name: 'IrisIncrement', variableId: 'IStep' },
	{ name: 'ZoomIncrement', variableId: 'ZStep' },
	{ name: 'RollIncrement', variableId: 'RStep' },
	{ name: 'PanSpeedLimit', variableId: 'PanSpeedLimit' },
	{ name: 'TiltSpeedLimit', variableId: 'TiltSpeedLimit' },
	{ name: 'M3SpeedLimit', variableId: 'M3SpeedLimit' },
	{ name: 'M4SpeedLimit', variableId: 'M4SpeedLimit' },
	{ name: 'TN1SpeedLimit', variableId: 'TN1SpeedLimit' },
	{ name: 'TN2SpeedLimit', variableId: 'TN2SpeedLimit' },
	{ name: 'TN3SpeedLimit', variableId: 'TN3SpeedLimit' },
	{ name: 'RollSpeedLimit', variableId: 'RollSpeedLimit' },
	{ name: 'FocusSpeedLimit', variableId: 'FocusSpeedLimit' },
	{ name: 'PanCruiseSpeed', variableId: 'PanCruiseSpeed' },
	{ name: 'TiltCruiseSpeed', variableId: 'TiltCruiseSpeed' },
	{ name: 'M3CruiseSpeed', variableId: 'M3CruiseSpeed' },
	{ name: 'M4CruiseSpeed', variableId: 'M4CruiseSpeed' },
	{ name: 'TN1CruiseSpeed', variableId: 'TN1CruiseSpeed' },
	{ name: 'TN2CruiseSpeed', variableId: 'TN2CruiseSpeed' },
	{ name: 'TN3CruiseSpeed', variableId: 'TN3CruiseSpeed' },
	{ name: 'RollCruiseSpeed', variableId: 'RollCruiseSpeed' },
	{ name: 'FocusCruiseSpeed', variableId: 'FocusCruiseSpeed' },
	{ name: 'PanInversion', variableId: 'PanInversion' },
	{ name: 'TiltInversion', variableId: 'TiltInversion' },
	{ name: 'M3Inversion', variableId: 'M3Inversion' },
	{ name: 'M4Inversion', variableId: 'M4Inversion' },
	{ name: 'TN1Inversion', variableId: 'TN1Inversion' },
	{ name: 'TN2Inversion', variableId: 'TN2Inversion' },
	{ name: 'TN3Inversion', variableId: 'TN3Inversion' },
	{ name: 'RollInversion', variableId: 'RollInversion' },
	{ name: 'FocusInversion', variableId: 'FocusInversion' },
	{ name: 'CurrentMotorSetup', variableId: 'CurrentMtrSet'},
	{ name: 'CurrentMotorStr', variableId: 'CurrentMtrStr'},
	{ name: 'CurrentMotorPosDirStr', variableId: 'CurrentMtrPosStr'},
	{ name: 'CurrentMotorNegDirStr', variableId: 'CurrentMtrNegStr'},
	{ name: 'CurrentMotorInversion', variableId: 'CurrentMtrInversion'},
	{ name: 'CurrentMotorSpeed', variableId: 'CurrentMtrSpeed'},
	{ name: 'CurrentPresetSetup', variableId: 'CurrentPstSet'},
	{ name: 'CurrentPresetSetupRun', variableId: 'CurrentPstSetRun'},
	{ name: 'CurrentPresetSetupRamp', variableId: 'CurrentPstSetRamp'},
	{ name: 'CurrentLoopSetup', variableId: 'CurrentLpSet'},
	{ name: 'CurrentLoopAPoint', variableId: 'CurrentLpA'},
	{ name: 'CurrentLoopBPoint', variableId: 'CurrentLpB'},
	{ name: 'CurrentLoopRunTime', variableId: 'CurrentLpRun'},
	{ name: 'CurrentLoopRampTime', variableId: 'CurrentLpRamp'},
	{ name: 'Preset0Status', variableId: 'Pst0Stat'},
	{ name: 'Preset0Pan', variableId: 'Pst0Pan'},
	{ name: 'Preset0Tilt', variableId: 'Pst0Tilt'},
	{ name: 'Preset0M3', variableId: 'Pst0M3'},
	{ name: 'Preset0M4', variableId: 'Pst0M4'},
	{ name: 'Preset0RunT', variableId: 'Pst0RunT'},
	{ name: 'Preset0RampT', variableId: 'Pst0RampT'},
	{ name: 'Loop0RunT', variableId: 'Lp0RunT'},
	{ name: 'Loop0RampT', variableId: 'Lp0RampT'},
	{ name: 'Loop0APoint', variableId: 'Lp0APoint'},
	{ name: 'Loop0BPoint', variableId: 'Lp0BPoint'},
	{ name: 'LoopActive', variableId: 'LpActive'},
	{ name: 'PanStopA', variableId: 'PanStopA'},
	{ name: 'PanStopB', variableId: 'PanStopB'},
	{ name: 'TiltStopA', variableId: 'TiltStopA'},
	{ name: 'TiltStopB', variableId: 'TiltStopB'},
	{ name: 'M3StopA', variableId: 'M3StopA'},
	{ name: 'M3StopB', variableId: 'M3StopB'},
	{ name: 'M4StopA', variableId: 'M4StopA'},
	{ name: 'M4StopB', variableId: 'M4StopB'},
	{ name: 'TNFocusStopA', variableId: 'TNFocusStopA'},
	{ name: 'TNFocusStopB', variableId: 'TNFocusStopB'},
	{ name: 'TNIrisStopA', variableId: 'TNIrisStopA'},
	{ name: 'TNIrisStopB', variableId: 'TNIrisStopB'},
	{ name: 'TNZoomStopA', variableId: 'TNZoomStopA'},
	{ name: 'TNZoomStopB', variableId: 'TNZoomStopB'},
	{ name: 'RSRollStopA', variableId: 'RSRollStopA'},
	{ name: 'RSRollStopB', variableId: 'RSRollStopB'},
	{ name: 'RSFocusStopA', variableId: 'RSFocusStopA'},
	{ name: 'RSFocusStopB', variableId: 'RSFocusStopB'},
	{ name: 'Last TCP Response', variableId: 'tcp_response' },
	{ name: 'Last Recalled Preset ID', variableId: 'LastPstID'},
	{ name: 'Preset 0 Info', variableId: 'Pts0Info'},
]

module.exports = async function (self) {self.setVariableDefinitions(variableList)}
module.exports.variableList = variableList